export const cardList = [
  {
    id: 1,
    theme: `Research`,
    title: `React HW`,
    date: `28.06.25`,
    status: `В работе`,
  },
  {
    id: 10,
    theme: `Copywriting`,
    title: `React HW`,
    date: `28.06.25`,
    status: `В работе`,
  },
  {
    id: 11,
    theme: `Web Design`,
    title: `React HW`,
    date: `28.06.25`,
    status: `В работе`,
  },
  {
    id: 2,
    theme: `Research`,
    title: `Практика создания превью`,
    date: `29.06.25`,
    status: `Нужно сделать`,
  },
  {
    id: 3,
    theme: `Research`,
    title: `Создание видео`,
    date: `30.06.25`,
    status: `Тестирование`,
  },
  {
    id: 4,
    theme: `Research`,
    title: `Тестирование OCR`,
    date: `30.06.25`,
    status: `Готово`,
  },
  {
    id: 5,
    theme: `Web Design`,
    title: `Тестовый текст`,
    date: `30.06.25`,
    status: `Без статуса`,
  },
  {
    id: 6,
    theme: `Research`,
    title: `Тестовый текст`,
    date: `30.06.25`,
    status: `Без статуса`,
  },
  {
    id: 7,
    theme: `Web Design`,
    title: `Тестовый текст`,
    date: `30.06.25`,
    status: `Без статуса`,
  },
  {
    id: 8,
    theme: `Copywriting`,
    title: `Тестовый текст`,
    date: `30.06.25`,
    status: `Без статуса`,
  },
  {
    id: 9,
    theme: `Research`,
    title: `Тестовый текст`,
    date: `30.06.25`,
    status: `Без статуса`,
  },
];
